// Aviso público en lenguaje cotidiano. La evidencia y el control de Play Console
// se conservan fuera del sitio: esta página no afirma una aprobación de Google.
const email='Tenkaitenshi354@gmail.com';
const chapter=(id,number,title,body)=>`<article class="privacy-chapter" id="${id}"><div class="privacy-chapter-heading"><span>${number}</span><h3>${title}</h3></div>${body}</article>`;
const p=text=>`<p>${text}</p>`;
const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
const permissionList=items=>`<dl class="privacy-permissions">${items.map(([name,use])=>`<div><dt>${name}</dt><dd>${use}</dd></div>`).join('')}</dl>`;
const playTopics=[['resumen','El modelo offline first'],['sin-nube','Sin nube de Tenkai'],['datos','Información en el equipo'],['respaldos','Copias y eliminación local'],['seguridad-local','Protección de tus archivos'],['host-client','Trabajo entre equipos'],['archivos','Fotos y documentos'],['apoya-creador','Compras y conexiones externas'],['music','Ejemplo: biblioteca multimedia'],['hardware-permisos','Permisos según la función'],['variaciones','Apps actuales y futuras'],['futuro','Cambios del aviso'],['contacto','Solicitudes de privacidad']];
const directTopics=[['pos-local','La información de tu tienda'],['licencias','Licencias y cambios de PC'],['nube','Boss y Sync'],['respaldos-nube','Copias conectadas'],['derechos','Conservación y solicitudes']];
const toc=(title,items)=>`<div><p>${title}</p><nav aria-label="${title}">${items.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></div>`;

export const privacyMain=`
<section class="page-hero section-shell privacy-hero">
 <p class="eyebrow">Privacidad · Última actualización: 5 de octubre de 2026</p>
 <h1>Tus datos.<br><em>Una explicación clara.</em></h1>
 <p class="lede">No todas las aplicaciones trabajan igual. Aquí puedes ver qué información permanece en tu equipo, cuándo se comparte y cómo pedir ayuda con tus datos.</p>
 <p class="privacy-owner">Responsable: <strong>Fernando Larios · TENKAITENSHI</strong><br>Contacto de privacidad: <a href="mailto:${email}">${email}</a></p>
 <div class="privacy-scope-grid">
  <a class="privacy-scope" href="#play-store"><span class="privacy-label">01 · Google Play</span><h2>Todas las aplicaciones<br>de Play Store</h2><p>Aviso general para las apps actuales y futuras de TENKAITENSHI: uso offline first, datos locales y permisos según cada función.</p><span class="card-link">Leer el aviso de Google Play →</span></a>
  <a class="privacy-scope" href="#programas-directos"><span class="privacy-label">02 · Instalación y servicios Tenkai</span><h2>POS y sus<br>aplicaciones conectadas</h2><p>Datos de la tienda, licencias, red local y los servicios opcionales Boss y Sync.</p><span class="card-link">Leer el aviso de POS →</span></a>
 </div>
</section>
<div class="section-shell privacy-layout">
 <aside class="privacy-toc"><p class="eyebrow">Encuentra tu tema</p>${toc('Aplicaciones de Google Play',playTopics)}${toc('Tenkai POS y servicios',directTopics)}<a class="privacy-contact-link" href="#solicitar-eliminacion">Pedir acceso, corrección o eliminación →</a></aside>
 <div class="privacy-body">
  <section class="privacy-policy" id="play-store" aria-labelledby="play-title">
   <div class="privacy-section-heading"><span class="privacy-label">01 · Política general de Google Play</span><h2 id="play-title">Aplicaciones de Play Store.<br>Privacidad en tu equipo.</h2><p>Este aviso cubre todas las aplicaciones de TENKAITENSHI publicadas en Google Play que enlazan esta política, incluidas las nuevas aplicaciones que se incorporen bajo el mismo modelo offline first. Los nombres y ejemplos de esta página explican funciones; no limitan el aviso a tres aplicaciones.</p><div class="privacy-model"><div><strong>Trabajo local</strong><span>Las tareas principales funcionan en tu dispositivo.</span></div><div><strong>Sin nube de Tenkai</strong><span>Tus registros y archivos no se guardan en nuestros servidores.</span></div><div><strong>Permisos con propósito</strong><span>Solo corresponden a las funciones que utiliza cada app.</span></div></div></div>
   ${chapter('resumen','01','Offline first: primero tu dispositivo',p('Las aplicaciones de esta familia están diseñadas para que sus tareas principales funcionen sin internet. Los datos que creas, importas o modificas se procesan y guardan localmente en tu dispositivo. No necesitas una cuenta Tenkai en la nube para realizar esas tareas.')+p('La conexión puede utilizarse para compras, restauraciones y actualizaciones de Google Play, novedades, enlaces externos o funciones entre equipos. Estas acciones tienen un alcance concreto y no convierten tus registros locales en una base de datos guardada en la nube de Tenkai.'))}
   ${chapter('sin-nube','02','Tus datos no se almacenan en una nube Tenkai',p('Las aplicaciones de Play Store cubiertas por este aviso no ofrecen almacenamiento ni sincronización de tus datos de trabajo en servidores de Tenkai. No subimos sus bases de clientes, proyectos, cotizaciones, documentos, biblioteca multimedia ni otros registros locales a una cuenta o nube propia.')+p('Tenkai no recibe una copia de esos archivos por el simple hecho de instalar o utilizar la app. No vendemos tus datos locales ni los usamos para crear perfiles publicitarios. Si decides exportar, compartir o guardar una copia en otro servicio, ese destino recibe la información que tú entregas y aplica sus propias condiciones.')+p('Las copias que Android o tu proveedor de almacenamiento puedan realizar según tus ajustes son independientes de Tenkai. Puedes revisar esas opciones en tu dispositivo. Boss y Sync, descritos en el segundo apartado, son servicios de la operación POS y no forman parte de esta familia de apps de Play Store.'))}
   ${chapter('datos','03','Qué información puedes guardar localmente',p('Cada app utiliza solo los tipos de información que necesita para sus funciones. Según la herramienta, puedes guardar:')+list(['Configuración: idioma, apariencia, preferencias y opciones de uso.','Trabajo y cálculos: materiales, costos, medidas, equipos, proyectos y parámetros de fabricación.','Organización comercial: productos, inventario, presupuestos, cotizaciones, importes, pagos y datos de clientes, como nombres o teléfonos, que decides registrar.','Archivos y multimedia: documentos, imágenes, audio, video, carátulas y sus datos descriptivos.','Actividad local: listas, favoritos, estadísticas de uso de la función y alarmas o recordatorios, cuando la app los incluye.'])+p('No todas las aplicaciones acceden a todos esos datos. Una calculadora utiliza los datos de sus cálculos; un reproductor utiliza tu biblioteca autorizada. La información se usa para la tarea que elegiste, dentro del equipo. Evita registrar datos personales que no necesites.'))}
   ${chapter('respaldos','04','Copias, conservación y eliminación',p('Los registros locales se conservan hasta que los eliminas mediante las opciones disponibles, borras los datos de la aplicación o desinstalas. Antes de hacerlo, guarda una copia si necesitas conservar tu trabajo.')+p('Los archivos originales, documentos exportados y copias guardadas en carpetas públicas pueden permanecer después de desinstalar. Para borrarlos, elimina también esas copias desde su ubicación. Si elegiste correo o almacenamiento en línea como destino, gestiona su eliminación en ese servicio.')+p('Tenkai no puede recuperar ni borrar a distancia una base que solo está en tu dispositivo. Tampoco puede recuperar un archivo local eliminado si no conservaste un respaldo. Puedes solicitar orientación por el contacto de privacidad.'))}
   ${chapter('seguridad-local','05','Protege lo que guardas en tu equipo',p('El acceso a los archivos se gestiona mediante las opciones y permisos del dispositivo. Protege su desbloqueo, revisa quién puede usarlo y comparte únicamente los documentos necesarios.')+p('Un respaldo completo puede incluir más información que un documento individual. Revisa su contenido, el destinatario y la carpeta o aplicación donde lo guardas. El aviso no supone que todos los archivos exportados estén cifrados ni que otras personas no puedan abrir una copia que les entregaste.'))}
   ${chapter('host-client','06','Conexiones locales y trabajo entre equipos',p('Si una aplicación incluye conexión con impresoras, accesorios u otros equipos, utiliza la información necesaria para la acción que inicias: imprimir, transferir archivos o intercambiar registros por la red local o una conexión cercana. Esto no requiere almacenar tu trabajo en servidores de Tenkai.')+p('Autoriza solo los equipos correctos y comprueba qué contenido envías. Un archivo que entregas a otra persona queda bajo su control. La operación de POS, Inventory, MultiPos y Resguard se explica por separado en el segundo apartado.'))}
   ${chapter('archivos','07','Imágenes, archivos y documentos',p('Las funciones de selección, importación, edición y exportación utilizan los archivos necesarios para la tarea. Elegir una imagen para un logotipo, por ejemplo, no publica tu galería. Un reproductor puede consultar la biblioteca de audio o video que le autorizas a leer.')+p('Al imprimir, compartir o abrir un archivo con otra aplicación, esta recibe el contenido que le entregas. Revisa también la privacidad de la impresora, aplicación o servicio que utilizas. La selección o importación local no sube por sí misma el archivo a Tenkai.'))}
   ${chapter('apoya-creador','08','Google Play y conexiones externas',p('Cuando una app incluye compras o aportaciones opcionales, Google Play procesa la cuenta y el pago. La app recibe el producto adquirido y el estado de la compra o restauración para habilitar lo correspondiente. Tenkai no recibe el número completo de tu tarjeta desde ese proceso.')+p('La consulta de actualizaciones puede ejecutarse al iniciar la aplicación o al abrir sus opciones, según la versión. Google Play comprueba si hay una versión disponible; la app te presenta la actualización cuando corresponde. Esa comprobación no envía a Tenkai tus clientes, documentos, proyectos o biblioteca multimedia.')+p('Al abrir novedades, enlaces, contacto o servicios de terceros, el proveedor puede recibir datos de conexión como la dirección de internet y la solicitud realizada. Google administra los datos de su cuenta, compras y servicios conforme a su política. El uso offline first no significa que Google Play u otro servicio que utilizas deje de procesar información.')+p('Si compartes un archivo por WhatsApp, correo, una tienda, PayPal u otra aplicación, el destino recibe lo que envías. Esas acciones no son un respaldo automático de Tenkai. Se utilizan únicamente cuando la función está disponible y decides usarla.')+`<p class="privacy-provider-links"><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Privacidad de Google</a><a href="https://www.paypal.com/mx/legalhub/paypal/privacy-full" target="_blank" rel="noopener noreferrer">Privacidad de PayPal</a><a href="https://www.whatsapp.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Privacidad de WhatsApp</a></p>`)}
   ${chapter('music','09','Ejemplo: una biblioteca multimedia',p('En una app como Tenkai Music, los archivos autorizados se utilizan para reproducir y organizar tu biblioteca o editar su información. Puede leer nombres, rutas, títulos, artistas, álbumes, años y carátulas. Las listas, favoritos, preferencias, estadísticas de escucha y alarmas se guardan localmente; tus canciones y ese historial no se envían a una biblioteca Tenkai en la nube.')+p('Al importar o copiar archivos, las carpetas públicas Music/Tenkai Music y Movies/Tenkai Music pueden conservar esas copias aunque desinstales la app. Quitar un elemento de la biblioteca no equivale a borrar todas sus copias. Para eliminar archivos, utiliza la opción correspondiente y confirma la solicitud de Android cuando aparezca.')+p('Los controles de reproducción y las alarmas pueden requerir notificaciones, actividad en segundo plano, alarmas y recordatorios o pantalla completa, según Android y la función utilizada. Se usan para reproducir, mostrar controles o sonar a la hora que configuraste. Music no necesita grabar con el micrófono para reproducir tus archivos.'))}
   ${chapter('hardware-permisos','10','Permisos según la función de cada app',p('Un permiso permite realizar una tarea concreta. Cada aplicación solicita únicamente los permisos correspondientes a sus funciones y a la versión del sistema. Este listado explica su alcance; no significa que todas las aplicaciones pidan todos los permisos.')+permissionList([['Archivos, imágenes y almacenamiento','Seleccionar, leer, guardar, editar, importar, exportar o compartir el contenido que utiliza la función.'],['Audio y video','Consultar y reproducir la biblioteca autorizada; organizar o copiar archivos cuando utilizas esas opciones.'],['Cámara o micrófono, si una app incluye esa función','Tomar una imagen, leer un código o capturar audio para una tarea local que eliges. No son necesarios para todas las aplicaciones ni para reproducir archivos existentes.'],['Bluetooth, red local o dispositivos cercanos','Conectar con impresoras, accesorios o equipos autorizados e intercambiar el contenido necesario para esa tarea, cuando la app lo permita.'],['Notificaciones y actividad en segundo plano','Mostrar controles de reproducción, avisos o recordatorios y mantener activa la función que estás utilizando.'],['Alarmas, recordatorios y pantalla completa','Programar y mostrar la alarma que configuraste, cuando la app incluye esa herramienta y Android lo permite.'],['Internet','Compras y restauraciones de Google Play, comprobación de actualizaciones, novedades y enlaces o servicios externos. No habilita una copia de tus registros en una nube Tenkai.']])+p('Puedes revisar o revocar los permisos en Ajustes de Android. Rechazar uno puede limitar la función que lo necesita sin conceder acceso a los demás datos. Los permisos sensibles que requieran una autorización del sistema se solicitan antes de acceder al recurso.')+p('Un permiso no autoriza por sí solo usos ajenos a la función explicada. Si una nueva aplicación necesita un tipo de dato o un propósito adicional, se incorpora su explicación a este aviso y a la propia app antes de utilizarlo.'))}
   ${chapter('variaciones','11','Todas las apps actuales y futuras',p('Esta es la política general de privacidad de la familia TENKAITENSHI en Google Play. Las nuevas publicaciones bajo el mismo modelo quedan comprendidas al enlazar este aviso. Calculator 3D, Forge Suite y Tenkai Music son ejemplos actuales de cálculo, fabricación y multimedia; no son una lista cerrada.')+p('Los datos concretos, permisos y conexiones dependen de las funciones de cada app. La ficha de Google Play y los avisos dentro de la aplicación identifican esas funciones. Compartir una política no significa que un reproductor acceda a datos de clientes ni que una calculadora necesite tus archivos de audio.')+p('El principio común es el uso offline first y el almacenamiento local de tus datos de trabajo, sin un servicio de nube Tenkai para estas aplicaciones. Los servicios conectados de POS tienen su propio apartado y tratamiento.'))}
   ${chapter('futuro','12','Nuevas funciones y cambios del aviso',p('La fecha al inicio indica la última actualización. Las nuevas aplicaciones mantienen el modelo descrito y explican los permisos que realmente necesitan. Si una función cambia el tratamiento de datos o incorpora un uso que aquí no está descrito, actualizamos este aviso antes de aplicarlo.')+p('Los usos nuevos que requieran tu autorización se explican también dentro de la app antes de solicitarla. Enlazar esta política no concede acceso a todos los datos ni sustituye los permisos del dispositivo.'))}
   ${chapter('contacto','13','Tu contacto para privacidad',p(`El responsable es Fernando Larios · TENKAITENSHI. Escribe a <a href="mailto:${email}">${email}</a> e indica la aplicación, la función y lo que necesitas consultar, corregir o eliminar. No adjuntes tu base de clientes, credenciales ni documentos de terceros para hacer una consulta inicial.`)+p('En las aplicaciones de esta familia no hay una cuenta Tenkai en la nube que debas cerrar para borrar tus registros locales. Su eliminación se gestiona en el dispositivo y en las copias que hayas guardado. Podemos orientarte sobre su ubicación; las solicitudes relacionadas con compras o una cuenta de Google se gestionan también mediante las opciones de Google.'))}
  </section>
  <section class="privacy-policy" id="programas-directos" aria-labelledby="direct-title">
   <div class="privacy-section-heading"><span class="privacy-label">02 · POS y servicios Tenkai</span><h2 id="direct-title">La tienda, las conexiones<br>y tu licencia.</h2><p>Corresponde a Tenkai POS, Inventory, MultiPos, Resguard y, cuando se contratan o habilitan, Boss y Sync. Una conexión local, una verificación de licencia y una sincronización en la nube son procesos diferentes.</p></div>
   ${chapter('pos-local','01','Los registros de tu tienda',p('POS conserva en el equipo la información necesaria para operar: productos, precios, costos, existencias, proveedores, ventas, devoluciones, mermas, caja, cortes, clientes, saldos, abonos, apartados, usuarios y permisos, según los módulos utilizados.')+p('Inventory guarda el catálogo descargado y los lotes, conteos o recepciones que preparas. MultiPos intercambia operaciones de caja con el POS autorizado. Resguard conserva la copia preparada para contingencia y las operaciones pendientes de conciliar. Los equipos vinculados pueden recibir datos necesarios para su tarea dentro de la red de la tienda.')+p('Los registros y copias locales quedan bajo el control de tu negocio y de los usuarios a quienes das acceso. Autoriza solo los equipos correctos, limita los permisos y protege las copias. El negocio decide qué datos de sus clientes registra y debe informarles del uso que hace de ellos.'))}
   ${chapter('licencias','02','Activación, verificación y cambios de PC',p('Para emitir, verificar, recuperar o migrar una licencia se utilizan datos de la licencia y la instalación: aplicación, edición, módulos, estado, identificadores del equipo y de la instalación, versión, fecha de instalación y nombre del negocio. La conexión puede aportar su dirección de internet y estado para atender y proteger el servicio.')+p('La gestión comercial de la licencia puede incluir el nombre del comprador y del negocio. Estos datos del comprador del software son distintos de la lista de clientes de la tienda. La comprobación de licencia no necesita enviar tickets, nombres de clientes, teléfonos, abonos ni la base comercial completa.')+p('Tenkai Care renueva el acceso a actualizaciones por otro año e incluye hasta dos cambios de PC asistidos al año. Para una migración se comprueba la licencia y el cambio de equipo. Esto no equivale a guardar automáticamente una copia de tu tienda en la nube.'))}
   ${chapter('nube','03','Lo que comparten Boss y Sync',p('Cuando habilitas el servicio conectado, se envía información de la organización, sucursales y dispositivos autorizados para compartir catálogo y precios, consultar existencias y mostrar la operación de las tiendas en Boss.')+list(['Catálogo: identificadores y nombres de productos, precios, costos, existencias y cambios que publicas.','Operación: ventas y sus artículos, devoluciones, movimientos de inventario, producción, pagos a proveedores y cortes, según la versión y los módulos.','Finanzas: importes en efectivo, tarjeta y otros medios, fondos de caja, entradas, salidas, saldos y reportes de la sucursal.','Referencias: folios, usuarios y dispositivos que hicieron una operación; ciertos eventos también incluyen referencias de clientes, abonos o cancelaciones de apartados y los motivos registrados.'])+p('Esta sincronización es diferente de la verificación de licencia. No debe suponerse que envía únicamente totales: algunas operaciones conservan su detalle y los campos que tu tienda registró. Evita escribir datos personales innecesarios en notas o motivos.')+p('Los importes de ventas con tarjeta no requieren capturar el número completo de la tarjeta ni su código de seguridad. No introduzcas esos datos en notas, nombres de productos ni otros campos libres.')+p('La información se almacena en el servicio conectado de Tenkai y se consulta con las credenciales y permisos de la organización. Boss conserva las credenciales en el almacenamiento protegido del dispositivo y usa la cámara cuando abres el lector de códigos. Una sucursal sin conexión puede mostrar información anterior hasta que vuelva a reportar.')+p('Tenkai utiliza Cloudflare como proveedor de alojamiento y almacenamiento para estos servicios. Las comunicaciones del servicio usan conexiones protegidas; cuida también tus accesos, equipos y red. Compartir una credencial permite actuar con sus permisos.')+`<p class="privacy-provider-links"><a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Privacidad de Cloudflare</a><a href="conexiones.html">Cómo se conectan las aplicaciones</a></p>`)}
   ${chapter('respaldos-nube','04','Un respaldo completo requiere cuidado',p('Tus respaldos locales pueden contener toda la tienda, incluidos datos de clientes, proveedores, usuarios y operaciones. Guardarlos o entregarlos a otra persona comparte más información que enviar un reporte.')+p('El respaldo conectado depende de que esa función esté disponible y habilitada en tu instalación y servicio. No se incluye automáticamente por instalar POS o renovar Care. Antes de utilizarlo, confirma qué se envía, quién puede recuperarlo y qué copias se conservan.')+p('No confundas la rotación de copias de respaldo con la eliminación de ventas, eventos o licencias: son registros distintos. Conserva además una copia propia cuando necesites recuperar tu negocio.'))}
   ${chapter('derechos','05','Cuánto permanecen y cómo solicitar cambios',p('En el equipo, los datos permanecen hasta que el negocio los elimina o sustituye mediante las funciones disponibles. Los respaldos y archivos exportados permanecen en el destino que elegiste hasta que también los eliminas.')+p('En el servicio conectado, cerrar Boss, desconectar una sucursal o dejar de sincronizar no borra automáticamente los registros ya enviados. La información almacenada permanece hasta que se gestiona su eliminación. Si quieres acceder a ella, corregirla o solicitar su baja, utiliza el contacto de privacidad y señala la organización o licencia correspondiente.')+p('La solicitud se revisa con quien está autorizado para esa organización o licencia, para evitar borrar información ajena. Se distinguen los datos operativos de los registros necesarios para acreditar una licencia, una migración, una compra o atender una obligación aplicable; si alguna información debe conservarse, se explica al atender la solicitud. No se promete que toda la información expire a los tres días.')+p('Si eres cliente de una tienda que usa POS, comienza por esa tienda: es quien decide cómo utiliza tus datos comerciales y controla sus registros y copias. Puedes escribir a Tenkai si necesitas aclarar el tratamiento de los servicios conectados.'))}
  </section>
  <section class="privacy-request" id="solicitar-eliminacion" aria-labelledby="request-title"><span class="privacy-label">Un contacto directo</span><h2 id="request-title">Acceso, corrección<br>o eliminación de datos.</h2><p>Envía una solicitud por correo. No necesitas reinstalar una aplicación para pedir la revisión de datos almacenados en un servicio Tenkai.</p><ol><li>Indica la aplicación o servicio.</li><li>Explica qué información o acción quieres revisar.</li><li>Si es POS o Sync, indica tu negocio o referencia de licencia, sin enviar contraseñas.</li><li>Te indicaremos cómo comprobar tu autorización y gestionar la solicitud.</li></ol><a class="button primary" href="mailto:${email}?subject=Solicitud%20de%20privacidad%20Tenkai">Solicitar por correo</a><p class="small-note">${email} · No envíes contraseñas, códigos de acceso, tarjetas ni una base completa como primer mensaje.</p></section>
  <section class="privacy-site"><h2>Al visitar esta web</h2><p>El proveedor de alojamiento, GitHub Pages, recibe los datos de conexión necesarios para servir las páginas, como la dirección de internet y la solicitud realizada. Este sitio no incorpora herramientas publicitarias de seguimiento. Al abrir WhatsApp, correo, Google Play o una descarga, continúas en el servicio correspondiente.</p><p><a href="https://docs.github.com/es/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">Privacidad de GitHub</a> · <a href="terminos-licencia-eula.html">Condiciones de licencia de POS</a></p></section>
 </div>
</div>`;
