// Aviso público en lenguaje cotidiano. La evidencia y el control de Play Console
// se conservan fuera del sitio: esta página no afirma una aprobación de Google.
const email='Tenkaitenshi354@gmail.com';
const chapter=(id,number,title,body)=>`<article class="privacy-chapter" id="${id}"><div class="privacy-chapter-heading"><span>${number}</span><h3>${title}</h3></div>${body}</article>`;
const p=text=>`<p>${text}</p>`;
const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
const playTopics=[['resumen','En pocas palabras'],['datos','Información en el equipo'],['respaldos','Copias y eliminación local'],['host-client','Trabajo entre equipos'],['archivos','Fotos y documentos'],['apoya-creador','Compras y enlaces externos'],['music','Biblioteca de Tenkai Music'],['hardware-permisos','Permisos y conexiones'],['variaciones','Alcance por aplicación'],['futuro','Cambios del aviso'],['contacto','Solicitudes de privacidad']];
const directTopics=[['pos-local','La información de tu tienda'],['licencias','Licencias y cambios de PC'],['nube','Boss y Sync'],['respaldos-nube','Copias conectadas'],['derechos','Conservación y solicitudes']];
const toc=(title,items)=>`<div><p>${title}</p><nav aria-label="${title}">${items.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></div>`;

export const privacyMain=`
<section class="page-hero section-shell privacy-hero">
 <p class="eyebrow">Privacidad · Última actualización: 5 de octubre de 2026</p>
 <h1>Tus datos.<br><em>Una explicación clara.</em></h1>
 <p class="lede">No todas las aplicaciones trabajan igual. Aquí puedes ver qué información permanece en tu equipo, cuándo se comparte y cómo pedir ayuda con tus datos.</p>
 <p class="privacy-owner">Responsable: <strong>Fernando Martín Crescencio Larios · TENKAITENSHI</strong><br>Contacto de privacidad: <a href="mailto:${email}">${email}</a></p>
 <div class="privacy-scope-grid">
  <a class="privacy-scope" href="#play-store"><span class="privacy-label">01 · Google Play</span><h2>Cálculo, fabricación<br>y música</h2><p>Calculator 3D, Forge Suite y Tenkai Music: trabajo local, archivos y compras opcionales en Google Play.</p><span class="card-link">Leer el aviso de estas apps →</span></a>
  <a class="privacy-scope" href="#programas-directos"><span class="privacy-label">02 · Instalación y servicios Tenkai</span><h2>POS y sus<br>aplicaciones conectadas</h2><p>Datos de la tienda, licencias, red local y los servicios opcionales Boss y Sync.</p><span class="card-link">Leer el aviso de POS →</span></a>
 </div>
</section>
<div class="section-shell privacy-layout">
 <aside class="privacy-toc"><p class="eyebrow">Encuentra tu tema</p>${toc('Aplicaciones de Google Play',playTopics)}${toc('Tenkai POS y servicios',directTopics)}<a class="privacy-contact-link" href="#solicitar-eliminacion">Pedir acceso, corrección o eliminación →</a></aside>
 <div class="privacy-body">
  <section class="privacy-policy" id="play-store" aria-labelledby="play-title">
   <div class="privacy-section-heading"><span class="privacy-label">01 · Google Play</span><h2 id="play-title">Calculator, Forge Suite<br>y Tenkai Music.</h2><p>Este apartado corresponde a Tenkai Calculator 3D (Tenkai C3D), Tenkai Forge Suite (Tenkai FS) y Tenkai Music. Sus funciones principales no requieren crear una cuenta Tenkai. Las demás aplicaciones Tenkai se distribuyen desde esta web.</p></div>
   ${chapter('resumen','01','En pocas palabras',p('Los cálculos, registros de trabajo y ajustes de tu biblioteca musical se guardan en tu dispositivo. Usar estas herramientas no significa contratar Sync ni enviar tu base de trabajo o tus canciones a una cuenta Tenkai.')+p('Algunas acciones sí usan internet: consultar novedades, abrir una página externa o realizar y restaurar una compra en Google Play. Se describen a continuación para distinguirlas del trabajo local.'))}
   ${chapter('datos','02','La información que introduces',p('Según la aplicación y la función utilizada, puedes guardar:')+list(['Materiales, costos, medidas, equipos, parámetros de fabricación y preferencias.','Proyectos, productos, presupuestos, cotizaciones, importes, pagos e inventario.','Nombres, teléfonos y otros datos de clientes que tú decides registrar para tu trabajo.'])+p('Estos registros permiten calcular, organizar y generar documentos. No se envía automáticamente esa base de clientes, proyectos o cotizaciones a un servidor Tenkai por utilizar las funciones locales. Evita registrar información que no necesites.'))}
   ${chapter('respaldos','03','Copias, conservación y eliminación',p('Los registros locales se conservan hasta que los eliminas mediante las opciones disponibles, borras los datos de la aplicación o desinstalas. Antes de hacerlo, guarda una copia si necesitas conservar tu trabajo.')+p('Cuando exportas un respaldo o un documento, eliges su destino. Esa copia puede permanecer aunque borres la app: elimínala también del almacenamiento, correo o servicio donde la hayas guardado. Las copias que realice Android o tu proveedor de almacenamiento dependen de la configuración de tu dispositivo; se gestionan por separado.'))}
   ${chapter('host-client','04','Cuando compartes con otro equipo',p('No necesitas conectar Calculator 3D ni Forge Suite con Tenkai POS para realizar sus tareas principales. Si una función o edición permite importar, exportar o intercambiar registros con otro equipo, se comparte la información elegida para esa operación.')+p('Un archivo que entregas a otra persona queda bajo su control. Comprueba el destinatario y evita compartir respaldos completos cuando solo necesitas enviar una cotización. La conexión de POS, Inventory, MultiPos y Resguard se explica en el segundo apartado.'))}
   ${chapter('archivos','05','Fotos, archivos y documentos',p('Puedes seleccionar imágenes, logotipos o archivos para incorporarlos a tu trabajo y generar documentos como presupuestos o archivos para imprimir. La selección permite usar el recurso que elegiste para esa tarea; no implica publicar todas tus fotos.')+p('Al imprimir, compartir o abrir un archivo con otra aplicación, esta recibe el contenido que le entregas. Revisa también la privacidad de la impresora, aplicación o servicio que utilizas.'))}
   ${chapter('apoya-creador','06','Compras y servicios externos',p('Las compras opcionales, aportaciones y funciones asociadas a Google Play utilizan su sistema de cobro. Google procesa la cuenta y el pago; la app recibe el producto adquirido y el estado de la compra o restauración para habilitar lo correspondiente. Tenkai no recibe el número completo de tu tarjeta desde este proceso.')+p('Los enlaces que tú abres pueden llevarte a tiendas, redes sociales, WhatsApp, PayPal u otros sitios. Esos servicios reciben los datos necesarios para atender tu visita o solicitud según sus propias políticas. Si envías una cotización por WhatsApp, por ejemplo, compartes ese documento con el contacto elegido.')+`<p class="privacy-provider-links"><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Privacidad de Google</a><a href="https://www.paypal.com/mx/legalhub/paypal/privacy-full" target="_blank" rel="noopener noreferrer">Privacidad de PayPal</a><a href="https://www.whatsapp.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Privacidad de WhatsApp</a></p>`)}
   ${chapter('music','07','Tu biblioteca de Tenkai Music',p('Music accede a los archivos de audio y video que autorizas para reproducirlos, organizar la biblioteca y editar su información. Puede leer nombres, rutas, títulos, artistas, álbumes, años y carátulas. Guarda localmente listas, favoritos, preferencias, estadísticas de escucha y alarmas que configuras; no envía automáticamente tus canciones ni ese historial a una biblioteca Tenkai en la nube.')+p('Al importar o copiar archivos, las carpetas públicas Music/Tenkai Music y Movies/Tenkai Music pueden conservar esas copias aunque desinstales la app. Quitar un elemento de la biblioteca no equivale a borrar todas sus copias. Para eliminar archivos, utiliza la opción correspondiente y confirma la solicitud de Android cuando aparezca.')+p('Los permisos de audio, video o almacenamiento permiten consultar la biblioteca del dispositivo o las carpetas elegidas. Los controles de reproducción y las alarmas pueden requerir notificaciones, actividad en segundo plano, alarmas y recordatorios o pantalla completa, según Android y la función utilizada. Se usan para reproducir, mostrar controles o sonar a la hora que configuraste; puedes revisarlos y revocarlos en Ajustes. Music no necesita grabar con el micrófono para reproducir tus archivos.'))}
   ${chapter('hardware-permisos','08','Permisos que tienen un propósito',list(['Archivos e imágenes: seleccionar, guardar, importar, exportar o compartir lo que utilizas en la tarea.','Audio y video en Music: leer y reproducir la biblioteca autorizada; copiar o editar archivos cuando utilizas esas opciones.','Notificaciones y alarmas en Music: controles de reproducción, recordatorios y alarmas que configuras.','Impresión y equipos cercanos: enviar el documento a la impresora o servicio que elegiste, cuando la versión lo permita.','Internet: compras y restauraciones de Google Play, consulta de versiones y enlaces o servicios que abres.'])+p('Los permisos disponibles varían por app y versión de Android. Una función que necesita un permiso puede dejar de funcionar si lo rechazas; puedes revisar los permisos en Ajustes de Android. Este aviso no supone que todas las apps soliciten cámara, micrófono, ubicación o todos los permisos a la vez.'))}
   ${chapter('variaciones','09','Cada app conserva su propio alcance',p('Calculator 3D se centra en cálculos, costos y cotizaciones. Forge Suite reúne herramientas de fabricación y organización. Music reproduce y organiza archivos multimedia y permite configurar alarmas. Este apartado describe los datos relacionados con esas funciones, incluidos los datos de clientes que tú capturas en las herramientas de trabajo y las compras opcionales.')+p('Boss y Sync trabajan con información remota de tiendas y tienen un tratamiento distinto. No debe interpretarse la operación local de estas tres aplicaciones como una promesa de que todos los productos Tenkai funcionan sin conexión o sin servicios externos.'))}
   ${chapter('futuro','10','Cambios de funciones y de este aviso',p('La fecha al inicio indica la última actualización. Si una app incorpora un uso nuevo de datos, este aviso debe actualizarse antes de aplicar ese tratamiento. Los permisos y las explicaciones que correspondan deben presentarse también dentro de la app; leer una página web no sustituye esas solicitudes.'))}
   ${chapter('contacto','11','Tu contacto para privacidad',p(`Escribe a <a href="mailto:${email}">${email}</a> e indica la aplicación, la función y lo que necesitas consultar, corregir o eliminar. No adjuntes tu base de clientes, credenciales ni documentos de terceros para hacer una consulta inicial.`)+p('Tenkai no puede borrar a distancia los archivos que solo están en tu dispositivo ni las copias que compartiste con otros servicios. Podemos orientarte sobre dónde se guardan y cómo eliminarlos.'))}
  </section>
  <section class="privacy-policy" id="programas-directos" aria-labelledby="direct-title">
   <div class="privacy-section-heading"><span class="privacy-label">02 · POS y servicios Tenkai</span><h2 id="direct-title">La tienda, las conexiones<br>y tu licencia.</h2><p>Corresponde a Tenkai POS, Inventory, MultiPos, Resguard y, cuando se contratan o habilitan, Boss y Sync. Una conexión local, una verificación de licencia y una sincronización en la nube son procesos diferentes.</p></div>
   ${chapter('pos-local','01','Los registros de tu tienda',p('POS conserva en el equipo la información necesaria para operar: productos, precios, costos, existencias, proveedores, ventas, devoluciones, mermas, caja, cortes, clientes, saldos, abonos, apartados, usuarios y permisos, según los módulos utilizados.')+p('Inventory guarda el catálogo descargado y los lotes, conteos o recepciones que preparas. MultiPos intercambia operaciones de caja con el POS autorizado. Resguard conserva la copia preparada para contingencia y las operaciones pendientes de conciliar. Los equipos vinculados pueden recibir datos necesarios para su tarea dentro de la red de la tienda.')+p('Los registros y copias locales quedan bajo el control de tu negocio y de los usuarios a quienes das acceso. Autoriza solo los equipos correctos, limita los permisos y protege las copias. El negocio decide qué datos de sus clientes registra y debe informarles del uso que hace de ellos.'))}
   ${chapter('licencias','02','Activación, verificación y cambios de PC',p('Para emitir, verificar, recuperar o migrar una licencia se utilizan datos de la licencia y la instalación: aplicación, edición, módulos, estado, identificadores del equipo y de la instalación, versión, fecha de instalación y nombre del negocio. La conexión puede aportar su dirección de internet y estado para atender y proteger el servicio.')+p('La gestión comercial de la licencia puede incluir el nombre del comprador y del negocio. Estos datos del comprador del software son distintos de la lista de clientes de la tienda. La comprobación de licencia no necesita enviar tickets, nombres de clientes, teléfonos, abonos ni la base comercial completa.')+p('Tenkai Care renueva el acceso a actualizaciones por otro año e incluye hasta dos cambios de PC asistidos al año. Para una migración se comprueba la licencia y el cambio de equipo. Esto no equivale a guardar automáticamente una copia de tu tienda en la nube.'))}
   ${chapter('nube','03','Lo que comparten Boss y Sync',p('Cuando habilitas el servicio conectado, se envía información de la organización, sucursales y dispositivos autorizados para compartir catálogo y precios, consultar existencias y mostrar la operación de las tiendas en Boss.')+list(['Catálogo: identificadores y nombres de productos, precios, costos, existencias y cambios que publicas.','Operación: ventas y sus artículos, devoluciones, movimientos de inventario, producción, pagos a proveedores y cortes, según la versión y los módulos.','Finanzas: importes en efectivo, tarjeta y otros medios, fondos de caja, entradas, salidas, saldos y reportes de la sucursal.','Referencias: folios, usuarios y dispositivos que hicieron una operación; ciertos eventos también incluyen referencias de clientes, abonos o cancelaciones de apartados y los motivos registrados.'])+p('Esta sincronización es diferente de la verificación de licencia. No debe suponerse que envía únicamente totales: algunas operaciones conservan su detalle y los campos que tu tienda registró. Evita escribir datos personales innecesarios en notas o motivos.')+p('Los importes de ventas con tarjeta no requieren capturar el número completo de la tarjeta ni su código de seguridad. No introduzcas esos datos en notas, nombres de productos ni otros campos libres.')+p('La información se almacena en el servicio conectado de Tenkai y se consulta con las credenciales y permisos de la organización. Boss conserva las credenciales en el almacenamiento protegido del dispositivo y usa la cámara cuando abres el lector de códigos. Una sucursal sin conexión puede mostrar información anterior hasta que vuelva a reportar.')+p('Tenkai utiliza Cloudflare como proveedor de alojamiento y almacenamiento para estos servicios. Las comunicaciones del servicio usan conexiones protegidas; cuida también tus accesos, equipos y red. Compartir una credencial permite actuar con sus permisos.')+`<p class="privacy-provider-links"><a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Privacidad de Cloudflare</a><a href="conexiones.html">Cómo se conectan las aplicaciones</a></p>`)}
   ${chapter('respaldos-nube','04','Un respaldo completo requiere cuidado',p('Tus respaldos locales pueden contener toda la tienda, incluidos datos de clientes, proveedores, usuarios y operaciones. Guardarlos o entregarlos a otra persona comparte más información que enviar un reporte.')+p('El respaldo conectado depende de que esa función esté disponible y habilitada en tu instalación y servicio. No se incluye automáticamente por instalar POS o renovar Care. Antes de utilizarlo, confirma qué se envía, quién puede recuperarlo y qué copias se conservan.')+p('No confundas la rotación de copias de respaldo con la eliminación de ventas, eventos o licencias: son registros distintos. Conserva además una copia propia cuando necesites recuperar tu negocio.'))}
   ${chapter('derechos','05','Cuánto permanecen y cómo solicitar cambios',p('En el equipo, los datos permanecen hasta que el negocio los elimina o sustituye mediante las funciones disponibles. Los respaldos y archivos exportados permanecen en el destino que elegiste hasta que también los eliminas.')+p('En el servicio conectado, cerrar Boss, desconectar una sucursal o dejar de sincronizar no borra automáticamente los registros ya enviados. La información almacenada permanece hasta que se gestiona su eliminación. Si quieres acceder a ella, corregirla o solicitar su baja, utiliza el contacto de privacidad y señala la organización o licencia correspondiente.')+p('La solicitud se revisa con quien está autorizado para esa organización o licencia, para evitar borrar información ajena. Se distinguen los datos operativos de los registros necesarios para acreditar una licencia, una migración, una compra o atender una obligación aplicable; si alguna información debe conservarse, se explica al atender la solicitud. No se promete que toda la información expire a los tres días.')+p('Si eres cliente de una tienda que usa POS, comienza por esa tienda: es quien decide cómo utiliza tus datos comerciales y controla sus registros y copias. Puedes escribir a Tenkai si necesitas aclarar el tratamiento de los servicios conectados.'))}
  </section>
  <section class="privacy-request" id="solicitar-eliminacion" aria-labelledby="request-title"><span class="privacy-label">Un contacto directo</span><h2 id="request-title">Acceso, corrección<br>o eliminación de datos.</h2><p>Envía una solicitud por correo. No necesitas reinstalar una aplicación para pedir la revisión de datos almacenados en un servicio Tenkai.</p><ol><li>Indica la aplicación o servicio.</li><li>Explica qué información o acción quieres revisar.</li><li>Si es POS o Sync, indica tu negocio o referencia de licencia, sin enviar contraseñas.</li><li>Te indicaremos cómo comprobar tu autorización y gestionar la solicitud.</li></ol><a class="button primary" href="mailto:${email}?subject=Solicitud%20de%20privacidad%20Tenkai">Solicitar por correo</a><p class="small-note">${email} · No envíes contraseñas, códigos de acceso, tarjetas ni una base completa como primer mensaje.</p></section>
  <section class="privacy-site"><h2>Al visitar esta web</h2><p>El proveedor de alojamiento, GitHub Pages, recibe los datos de conexión necesarios para servir las páginas, como la dirección de internet y la solicitud realizada. Este sitio no incorpora herramientas publicitarias de seguimiento. Al abrir WhatsApp, correo, Google Play o una descarga, continúas en el servicio correspondiente.</p><p><a href="https://docs.github.com/es/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">Privacidad de GitHub</a> · <a href="terminos-licencia-eula.html">Condiciones de licencia de POS</a></p></section>
 </div>
</div>`;
